/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const Payload$schema = z.object({
  'name': z.string(),
  'count': z.number().optional(),
}).describe('Runtime-validating data root.')

export const Payload = Payload$schema

export const TYPERT = {
  package: '@fixture/host',
  face: 'host',
  schemas: [
    { name: 'Payload', schema: Payload },
  ],
  model: {
    "services": [
      {
        "description": "Service exported only through a non-default alias.",
        "summary": "Service exported only through a non-default alias.",
        "tags": [],
        "jsDoc": "/** Service exported only through a non-default alias. */",
        "key": "aliased",
        "exportName": "PublicAliasedService",
        "members": [
          {
            "kind": "method",
            "name": "ready",
            "signature": "ready(): boolean",
            "summary": "Report readiness.",
            "jsDoc": "/** Report readiness. */"
          }
        ],
        "types": []
      },
      {
        "description": "Service exported only through the package default.",
        "summary": "Service exported only through the package default.",
        "tags": [],
        "jsDoc": "/** Service exported only through the package default. */",
        "key": "defaultOnly",
        "exportName": "default",
        "members": [
          {
            "kind": "method",
            "name": "ready",
            "signature": "ready(): boolean",
            "summary": "Report readiness.",
            "jsDoc": "/** Report readiness. */"
          }
        ],
        "types": []
      },
      {
        "description": "Fixture service with generic, mapped, and truly external boundary types.",
        "summary": "Fixture service with generic, mapped, and truly external boundary types.",
        "tags": [],
        "jsDoc": "/** Fixture service with generic, mapped, and truly external boundary types. */",
        "key": "demo",
        "exportName": "DemoService",
        "members": [
          {
            "kind": "method",
            "name": "inspect",
            "signature": "inspect(agent: Agent<{ ready: true }>, flags: Flags<Payload>): Present<Payload>",
            "summary": "Inspect one agent without flattening its generic state.",
            "jsDoc": "/** Inspect one agent without flattening its generic state. */"
          },
          {
            "kind": "method",
            "name": "acceptsExternal",
            "signature": "acceptsExternal(schema: ZodType<string>): void",
            "summary": "Keep an npm-owned type as External.",
            "jsDoc": "/** Keep an npm-owned type as External. */"
          },
          {
            "kind": "method",
            "name": "setPhase",
            "signature": "setPhase(phase: AgentPhase): void",
            "summary": "Accept a developer-authored enum without flattening it.",
            "jsDoc": "/** Accept a developer-authored enum without flattening it. */"
          },
          {
            "kind": "method",
            "name": "inspectSyntax",
            "signature": "inspectSyntax(zoo: SyntaxZoo): void",
            "summary": "Exercise every retained type-graph shape from a public boundary.",
            "jsDoc": "/** Exercise every retained type-graph shape from a public boundary. */"
          },
          {
            "kind": "method",
            "name": "inspectAsync",
            "signature": "async inspectAsync(zoo: SyntaxZoo): Promise<void>",
            "summary": "Preserve async source metadata without changing its type signature.",
            "jsDoc": "/** Preserve async source metadata without changing its type signature. */"
          },
          {
            "kind": "method",
            "name": "destructure",
            "signature": "destructure({ name }: Payload, [suffix]: [string]): string",
            "summary": "Retain an authored binding-pattern parameter.",
            "jsDoc": "/** Retain an authored binding-pattern parameter. */"
          }
        ],
        "types": [
          {
            "name": "AbstractEntity",
            "declaration": "export abstract class AbstractEntity implements Entity {\n    abstract readonly id: string;\n}"
          },
          {
            "name": "Added",
            "declaration": "export type Added<Value> = { readonly [Key in keyof Value]?: Value[Key] };"
          },
          {
            "name": "Agent",
            "declaration": "export class Agent<State extends object = { ready: boolean; }> implements Entity {\n    readonly id: string;\n    state: State;\n    get label(): string;\n    set label(value: string);\n    run<Value>(input: Box<Value>): Promise<Present<Value>>;\n}"
          },
          {
            "name": "AgentPhase",
            "declaration": "export enum AgentPhase {\n    Unknown,\n    Idle = 'idle',\n    Running = 'running',\n}"
          },
          {
            "name": "Box",
            "declaration": "export interface Box<T> {\n    readonly value: T;\n}"
          },
          {
            "name": "Callable",
            "declaration": "export interface Callable {\n    (value: string): number;\n    new (value: string): Entity;\n    readonly [key: string]: unknown;\n}"
          },
          {
            "name": "Entity",
            "declaration": "export interface Entity {\n    readonly id: string;\n}"
          },
          {
            "name": "Flags",
            "declaration": "export type Flags<T> = { readonly [K in keyof T]?: boolean };"
          },
          {
            "name": "Guards",
            "declaration": "export interface Guards {\n    isEntity(value: unknown): value is Entity;\n    isFluent(): this is Guards;\n    assertEntity(value: unknown): asserts value is Entity;\n    assertPresent(value: unknown): asserts value;\n    fluent(): this;\n}"
          },
          {
            "name": "Payload",
            "declaration": "export interface Payload {\n    name: string;\n    count?: number;\n}"
          },
          {
            "name": "PlainMap",
            "declaration": "export type PlainMap<Value> = { [Key in keyof Value]: Value[Key] };"
          },
          {
            "name": "Present",
            "declaration": "export type Present<T> = T extends null | undefined ? never : T;"
          },
          {
            "name": "Recursive",
            "declaration": "export interface Recursive extends Box<string> {\n    readonly next?: Recursive;\n}"
          },
          {
            "name": "Remapped",
            "declaration": "export type Remapped<Value> = { -readonly [Key in keyof Value as `get${Capitalize<string & Key>}`]-?: Value[Key] };"
          },
          {
            "name": "Result",
            "declaration": "export type Result<Value> = Value extends (...arguments_: never[]) => infer Output ? Output : never;"
          },
          {
            "name": "Route",
            "declaration": "export type Route<From extends string, To extends string> = `/${From}/to/${To}/end`;"
          },
          {
            "name": "StringResult",
            "declaration": "export type StringResult<Value> = Value extends readonly [infer Output extends string] ? Output : never;"
          },
          {
            "name": "SyntaxZoo",
            "declaration": "export interface SyntaxZoo {\n    anyValue: any;\n    bigintValue: bigint;\n    parenthesized: (Entity | null);\n    literals: 1 | 1n | -2 | -2n | false | `fixed`;\n    readonly uniqueToken: unique symbol;\n    intersection: Entity & { active: boolean; };\n    array: string[];\n    tuple: [head: string, count?: number, ...tail: boolean[]];\n    unnamedTuple: [string?, ...number[]];\n    readonlyTuple: readonly [string, number];\n    object: { readonly value?: string; 'quoted-name': number; 1: boolean; ['computed']: symbol; invoke?(input: number): void; };\n    callback: <Value extends Entity = Entity>(this: Entity, value: Value, optional?: string, ...rest: number[]) => Promise<Value>;\n    constCallback: <const Value extends readonly string[]>(value: Value) => Value;\n    factory: new <Value extends Entity>(value: Value) => Value;\n    abstractFactory: abstract new (id: string) => AbstractEntity;\n    indexed: Payload['name'];\n    inferred: Result<() => string>;\n    constrainedInfer: StringResult<['value']>;\n    topic: Topic<'ready'>;\n    route: Route<'source', 'target'>;\n    query: typeof phaseOrder;\n    instantiatedQuery: typeof genericFactory<string>;\n    imported: import('zod').ZodType<string>;\n    importedWith: import('zod', { with: { 'resolution-mode': 'import' } }).ZodType<string>;\n    importedModule: typeof import('zod');\n    process: NodeJS.Process;\n    callable: Callable;\n    guards: Guards;\n    variance: Variance<Entity, Payload, Box<string>>;\n    plainMap: PlainMap<Payload>;\n    remapped: Remapped<Payload>;\n    added: Added<Payload>;\n    abstractEntity: AbstractEntity;\n    recursive: Recursive;\n    tagOnly: TagOnly;\n    unpunctuated: Unpunctuated;\n}"
          },
          {
            "name": "TagOnly",
            "declaration": "export interface TagOnly {\n    readonly value: string;\n}"
          },
          {
            "name": "Topic",
            "declaration": "export type Topic<Name extends string> = `demo/${Name}`;"
          },
          {
            "name": "Unpunctuated",
            "declaration": "export interface Unpunctuated {\n    readonly value: string;\n}"
          },
          {
            "name": "Variance",
            "declaration": "export interface Variance<in Input, out Output, in out State> {\n    consume: (input: Input) => void;\n    readonly produce: () => Output;\n    state: State;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "tags": [],
        "name": "demo/property",
        "signature": "'demo/property'(payload: Payload): void"
      },
      {
        "description": "A generic fixture event.",
        "summary": "A generic fixture event.",
        "tags": [
          {
            "name": "param",
            "argument": "agent",
            "comment": "- emitting agent.",
            "text": "@param agent - emitting agent.\n     *"
          },
          {
            "name": "param",
            "argument": "payload",
            "comment": "- event payload.",
            "text": "@param payload - event payload.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * A generic fixture event.\n * @param agent - emitting agent.\n * @param payload - event payload.\n * @mode emit\n */",
        "name": "demo/ready",
        "mode": "emit",
        "signature": "'demo/ready'(agent: Agent<{ ready: true; }>, payload: Box<Payload>): void"
      },
      {
        "tags": [
          {
            "name": "mode",
            "comment": "serial",
            "text": "@mode serial"
          }
        ],
        "jsDoc": "/** @mode serial */",
        "name": "demo/serial-property",
        "mode": "serial",
        "signature": "'demo/serial-property'(payload: Payload): void"
      },
      {
        "tags": [],
        "name": "demo/unmodeled",
        "signature": "'demo/unmodeled'(): void"
      }
    ],
    "objects": [
      {
        "description": "Reference-passed capability object.",
        "summary": "Reference-passed capability object.",
        "tags": [
          {
            "name": "typert",
            "comment": "object",
            "text": "@typert object"
          }
        ],
        "jsDoc": "/**\n * Reference-passed capability object.\n * @typert object\n */",
        "name": "Agent",
        "exportName": "Agent",
        "members": [
          {
            "kind": "property",
            "name": "id",
            "signature": "readonly id: string"
          },
          {
            "kind": "property",
            "name": "state",
            "signature": "state: State"
          },
          {
            "kind": "getter",
            "name": "label",
            "signature": "get label(): string",
            "summary": "Read the public display label.",
            "jsDoc": "/** Read the public display label. */"
          },
          {
            "kind": "setter",
            "name": "label",
            "signature": "set label(value: string)",
            "summary": "Accept a public display label.",
            "jsDoc": "/** Accept a public display label. */"
          },
          {
            "kind": "method",
            "name": "run",
            "signature": "run<Value>(input: Box<Value>): Promise<Present<Value>>",
            "summary": "Run one typed input.",
            "jsDoc": "/** Run one typed input. */"
          }
        ],
        "types": [
          {
            "name": "Box",
            "declaration": "export interface Box<T> {\n    readonly value: T;\n}"
          },
          {
            "name": "Present",
            "declaration": "export type Present<T> = T extends null | undefined ? never : T;"
          }
        ]
      }
    ]
  },
}
