package middleware

// Ported from Goji's middleware, source:
// https://github.com/zenazn/goji/tree/master/web/middleware

import (
	"bufio"
	"bytes"
	"io"
	"log"
	"net"
	"net/http"
	"time"
)

// DefaultLogFormatter contains all the data needed to construct a log message
type DefaultLogFormatter struct {
	buf bytes.Buffer
}

// LogFormatter allows you to customize this middleware's output format.
type LogFormatter interface {
	FormatRequest(r *http.Request) LogFormatter
	FormatResponse(status, bytes int, elapsed time.Duration)
	Log()
	Recover(err error)
}

var defaultLogFormatter *DefaultLogFormatter

// Logger is a middleware that logs the start and end of each request, along
// with some useful data about what was requested, what the response status was,
// and how long it took to return. When standard output is a TTY, Logger will
// print in color, otherwise it will print in black and white.
//
// Logger prints a request ID if one is provided.
func Logger(next http.Handler) http.Handler {
	return FormattedLogger(defaultLogFormatter, next)
}

// FormattedLogger is a middleware that allows you to customize what is logged
// for each request/response.
func FormattedLogger(f LogFormatter, next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {
		ctx := f.FormatRequest(r)
		lw := wrapWriter(w)

		t1 := time.Now()
		defer func() {
			t2 := time.Now()
			ctx.FormatResponse(lw.Status(), lw.BytesWritten(), t2.Sub(t1))
			ctx.Log()
		}()

		next.ServeHTTP(lw, r)
	}

	return http.HandlerFunc(fn)
}

// FormatRequest stores info from the request, for use by Log()
func (l *DefaultLogFormatter) FormatRequest(r *http.Request) LogFormatter {
	var ctx DefaultLogFormatter

	reqID := GetReqID(r.Context())
	if reqID != "" {
		cW(&ctx.buf, nYellow, "[%s] ", reqID)
	}
	cW(&ctx.buf, nCyan, "\"")
	cW(&ctx.buf, bMagenta, "%s ", r.Method)

	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	cW(&ctx.buf, nCyan, "%s://%s%s %s\" ", scheme, r.Host, r.RequestURI, r.Proto)

	ctx.buf.WriteString("from ")
	ctx.buf.WriteString(r.RemoteAddr)
	ctx.buf.WriteString(" - ")

	return &ctx
}

// FormatResponse stores info from the response, for use by Log()
func (ctx *DefaultLogFormatter) FormatResponse(status, bytes int, elapsed time.Duration) {
	if status == StatusClientClosedRequest {
		cW(&ctx.buf, bRed, "[disconnected]")
	} else {
		switch {
		case status < 200:
			cW(&ctx.buf, bBlue, "%03d", status)
		case status < 300:
			cW(&ctx.buf, bGreen, "%03d", status)
		case status < 400:
			cW(&ctx.buf, bCyan, "%03d", status)
		case status < 500:
			cW(&ctx.buf, bYellow, "%03d", status)
		default:
			cW(&ctx.buf, bRed, "%03d", status)
		}
	}

	cW(&ctx.buf, bBlue, " %dB", bytes)

	ctx.buf.WriteString(" in ")
	if elapsed < 500*time.Millisecond {
		cW(&ctx.buf, nGreen, "%s", elapsed)
	} else if elapsed < 5*time.Second {
		cW(&ctx.buf, nYellow, "%s", elapsed)
	} else {
		cW(&ctx.buf, nRed, "%s", elapsed)
	}
}

// Log writes out the accumulated log data
func (ctx *DefaultLogFormatter) Log() {
	log.Print(ctx.buf.String())
}

// writerProxy is a proxy around an http.ResponseWriter that allows you to hook
// into various parts of the response process.
type writerProxy interface {
	http.ResponseWriter
	// Status returns the HTTP status of the request, or 0 if one has not
	// yet been sent.
	Status() int
	// BytesWritten returns the total number of bytes sent to the client.
	BytesWritten() int
	// Tee causes the response body to be written to the given io.Writer in
	// addition to proxying the writes through. Only one io.Writer can be
	// tee'd to at once: setting a second one will overwrite the first.
	// Writes will be sent to the proxy before being written to this
	// io.Writer. It is illegal for the tee'd writer to be modified
	// concurrently with writes.
	Tee(io.Writer)
	// Unwrap returns the original proxied target.
	Unwrap() http.ResponseWriter
}

// WrapWriter wraps an http.ResponseWriter, returning a proxy that allows you to
// hook into various parts of the response process.
func wrapWriter(w http.ResponseWriter) writerProxy {
	_, cn := w.(http.CloseNotifier)
	_, fl := w.(http.Flusher)
	_, hj := w.(http.Hijacker)
	_, rf := w.(io.ReaderFrom)

	bw := basicWriter{ResponseWriter: w}
	if cn && fl && hj && rf {
		return &fancyWriter{bw}
	}
	if fl {
		return &flushWriter{bw}
	}
	return &bw
}

// basicWriter wraps a http.ResponseWriter that implements the minimal
// http.ResponseWriter interface.
type basicWriter struct {
	http.ResponseWriter
	wroteHeader bool
	code        int
	bytes       int
	tee         io.Writer
}

func (b *basicWriter) WriteHeader(code int) {
	if !b.wroteHeader {
		b.code = code
		b.wroteHeader = true
		b.ResponseWriter.WriteHeader(code)
	}
}
func (b *basicWriter) Write(buf []byte) (int, error) {
	b.WriteHeader(http.StatusOK)
	n, err := b.ResponseWriter.Write(buf)
	if b.tee != nil {
		_, err2 := b.tee.Write(buf[:n])
		// Prefer errors generated by the proxied writer.
		if err == nil {
			err = err2
		}
	}
	b.bytes += n
	return n, err
}
func (b *basicWriter) maybeWriteHeader() {
	if !b.wroteHeader {
		b.WriteHeader(http.StatusOK)
	}
}
func (b *basicWriter) Status() int {
	return b.code
}
func (b *basicWriter) BytesWritten() int {
	return b.bytes
}
func (b *basicWriter) Tee(w io.Writer) {
	b.tee = w
}
func (b *basicWriter) Unwrap() http.ResponseWriter {
	return b.ResponseWriter
}

// fancyWriter is a writer that additionally satisfies http.CloseNotifier,
// http.Flusher, http.Hijacker, and io.ReaderFrom. It exists for the common case
// of wrapping the http.ResponseWriter that package http gives you, in order to
// make the proxied object support the full method set of the proxied object.
type fancyWriter struct {
	basicWriter
}

func (f *fancyWriter) CloseNotify() <-chan bool {
	cn := f.basicWriter.ResponseWriter.(http.CloseNotifier)
	return cn.CloseNotify()
}
func (f *fancyWriter) Flush() {
	fl := f.basicWriter.ResponseWriter.(http.Flusher)
	fl.Flush()
}
func (f *fancyWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	hj := f.basicWriter.ResponseWriter.(http.Hijacker)
	return hj.Hijack()
}
func (f *fancyWriter) ReadFrom(r io.Reader) (int64, error) {
	if f.basicWriter.tee != nil {
		return io.Copy(&f.basicWriter, r)
	}
	rf := f.basicWriter.ResponseWriter.(io.ReaderFrom)
	f.basicWriter.maybeWriteHeader()
	return rf.ReadFrom(r)
}

var _ http.CloseNotifier = &fancyWriter{}
var _ http.Flusher = &fancyWriter{}
var _ http.Hijacker = &fancyWriter{}
var _ io.ReaderFrom = &fancyWriter{}

type flushWriter struct {
	basicWriter
}

func (f *flushWriter) Flush() {
	fl := f.basicWriter.ResponseWriter.(http.Flusher)
	fl.Flush()
}

var _ http.Flusher = &flushWriter{}
